version: "3.7"

services:
  postgres:
    image: "postgres:14-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=jawstutorial
    ports:
      - 5432:5432
  pgadmin4:
    image: "dpage/pgadmin4"
    depends_on: [ postgres ]
    ports:
      - "8082:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=john.doe@example.com
      - PGADMIN_DEFAULT_PASSWORD=secret